---

- name: "Create IMM Server Profile Template"
  vars:
    api_info: &api_info_org_moid
      api_private_key: "{{ intersight_api_private_key }}"
      api_key_id: "{{ intersight_api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"
  cisco.intersight.intersight_rest_api:
    <<: *api_info_org_moid
    resource_path: /organization/Organizations
    query_params:
      $filter: "Name eq '{{ org_name }}'"
  register: intersight_org
  delegate_to: localhost
  tags: always
  run_once: true


- name: Collect policy information for Service Profile Template
  ansible.builtin.include_tasks: gather_policy_info.yml

- name: Create Server Profile Template for FC storage
  ansible.builtin.include_tasks: create_fc_server_profile_template.yml
  when: configure_fc == 'true'  

- name: Create Server Profile Template for iSCSI storage
  ansible.builtin.include_tasks: create_iscsi_server_profile_template.yml
  when: configure_iscsi == 'true'  
