---

- name: Add ESXi Hosts to vCenter
  community.vmware.vmware_host:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: '{{ vcenter_dc }}'
    cluster: '{{ vcenter_cluster }}'
    esxi_hostname: '{{ inventory_hostname }}'
    esxi_username: '{{ esxi_username }}'
    esxi_password: '{{ esxi_password }}'
    fetch_ssl_thumbprint: true
    validate_certs: false
    state: present
  delegate_to: localhost
