---
# Configuration Role for MDS.
#
- name: Configure Features
  ansible.builtin.include_tasks: configure_mds_features.yml
- name: Configure NTP Servers
  ansible.builtin.include_tasks: configure_mds_ntp.yml
- name: Configure Interface, Port-Channel and Trunk Settings
  ansible.builtin.include_tasks: configure_mds_interfaces.yml
- name: Configure vsan
  ansible.builtin.include_tasks: configure_mds_vsans.yml
- name: Configure Device Aliases
  ansible.builtin.include_tasks: configure_mds_da.yml
- name: Configure MDS Zone and Zoneset
  ansible.builtin.include_tasks: configure_mds_zones.yml
- name: Activate MDS Zoneset
  ansible.builtin.include_tasks: activate_mds_zoneset.yml
- name: Save Configuration
  ansible.builtin.include_tasks: save_mds_config.yml
