# ##############################################################################
#
# Host Setup Section
# ESXIhosts role configuration is common to both iSCSI and FC hosts
# ESXIiscsi role configuration is only applied to the iSCSI hosts
# If configure_fc or configure_iscsi are commented out, the host config will be skipped
# If inventory does not contain any servers under esxi_fc or esxi_iscsi sections, the config will be skipped
#
# ##############################################################################
---
- name: Configure VMware ESXi for iSCSI storage
  hosts: esxi_iscsi
  gather_facts: false
  serial: 1
  vars_files:
  roles:
    - role: vmware_esxi_iscsi
      when: configure_iscsi is defined

- name: Configure VMware ESXi for FC storage
  hosts: esxi_fc
  gather_facts: false
  serial: 1
  vars_files:
  roles:
    - role: vmware_esxi_hosts
      when: configure_fc is defined
