---
- name: Setup Cisco Intersight
  # hosts: localhost
  hosts: "{{ group | default('Dynamic_Inventory') }}"
  connection: local
  gather_facts: false
  vars_files:
  roles:
    - role: cisco_intersight_common

- name: Setup Cisco UCS servers
  # hosts: localhost
  hosts: cisco_imm_servers
  connection: local
  gather_facts: false
  vars_files:
  roles:
    - role: cisco_ucs_imm
