---
# These tasks perform necessary configurations in vCenter, add ESXi Hosts
# to vCenter and then configure the ESXi hosts for various parameters
#
# vCenter Configuration Tasks

- name: Create Datacenter object in vCenter
  ansible.builtin.include_tasks: create_dc.yml

# [specification of VM Swap for cluster not available at this time]
- name: Cluster creation for the provisioned hosts including setting up HA/DRS
  ansible.builtin.include_tasks: create_cluster.yml

- name: Create DVS within vCenter
  ansible.builtin.include_tasks: create_vds.yml

- name: Create DVS Portgroups
  ansible.builtin.include_tasks: create_vds_pg.yml
