---
vpc_source: 110.119.0.3
vpc_destination:  110.119.0.4
vpc_role_priority: "20"
iscsi_vlan: "3020"
vpc_domain_id: "10"

# If using N9k-A for NTP Distribution via IB-MGMT VLAN
# IB_MGMT_ntp_dist_IP: "{{ ib_mgmt_ntp_servers[0].ip_address }}{{ ntp_distribution_nm_cidr }}"
# Interface Lists; more interfaces can be added for additional BW

uplink_interface_list:
  - interface: "Ethernet1/93"
    description: "vPC to Upstream Network (Nexus-Core-1:p1/30)"
  - interface: "Ethernet1/94"
    description: "vPC to Upstream Network (Nexus-Core-2:p1/30)"

peerlink_interface_list:
  - interface: "Ethernet1/101"
    description: "AC09-N93360YC-FX2-1:Eth1/101"
  - interface: "Ethernet1/102"
    description: "AC09-N93360YC-FX2-1:Eth1/102"

FI_A_interface_list:
  - interface: "Ethernet1/97"
    description: "AC09-UCS-6536-FI-A:Eth1/32"

FI_B_interface_list:
  - interface: "Ethernet1/98"
    description: "AC09-UCS-6536-FI-B:Eth1/32"

# temp
# storage_interface_list:
#   - interface: "Ethernet1/95"
#     description: "AC09-Pure-FA-X50R3:CT0.eth5"
#   - interface: "Ethernet1/96"
#     description: "AC09-Pure-FA-X50R3:CT1.eth5"
#   - interface: "Ethernet1/103"
#     description: "AC09-Pure-FA-X50R3:CT0.eth15"
#   - interface: "Ethernet1/104"
#     description: "AC09-Pure-FA-X50R3:CT1.eth15"
    
# NEW
storage_interface_list:
  - interface: "Ethernet1/95"
    description: "AC09-Pure-FA-X50R3:CT0.eth5"
    vlan: "{{ storage_vlans['iscsi_b']['id'] }}"
  - interface: "Ethernet1/96"
    description: "AC09-Pure-FA-X50R3:CT1.eth5"
    vlan: "{{ storage_vlans['iscsi_b']['id'] }}"
  - interface: "Ethernet1/103"
    description: "AC09-Pure-FA-X50R3:CT0.eth15"
    vlan: "{{ storage_vlans['nvme_roce_b']['id'] }}"
  - interface: "Ethernet1/104"
    description: "AC09-Pure-FA-X50R3:CT1.eth15"
    vlan: "{{ storage_vlans['nvme_roce_b']['id'] }}"

all_interfaces: "{{ uplink_interface_list + peerlink_interface_list + FI_A_interface_list + FI_B_interface_list + nexus_b_storage_interface_list }}"

# VPC Parameters
#
uplink_PC:
  - interface: "port-channel119"
    # id must be same as port-channel number
    id: "119"
    speed: "auto"
    duplex: "auto"
    description: "vPC to Upstream Network (Nexus-Core-1:p1/30, Nexus-Core-2:p1/30)"
#
peerlink_PC:
  - interface: "port-channel100"
    # id must be same as port-channel number
    id: "100"
    speed: "auto"
    duplex: "auto"
    description: "vPC Peer Link to Nexus Peer switch"
#
FI_A_PC:
  - interface: "port-channel101"
    # id must be same as port-channel number
    id: "101"
    speed: "auto"
    duplex: "auto"
    description: "vPC to AC09-6536-FI-A"
#
FI_B_PC:
  - interface: "port-channel102"
    # id must be same as port-channel number
    id: "102"
    speed: "auto"
    duplex: "auto"
    description: "vPC to AC09-6536-FI-B"
#
all_port_channels: "{{ peerlink_PC + uplink_PC + FI_A_PC + FI_B_PC }}"
#