---
array_name: "AC09-FA-X50R3"
interfaces_fc:
  - port: ct0.fc0
  - port: ct0.fc1

interfaces_fc_nvme:
  - port: ct0.fc2
  - port: ct0.fc3

interfaces_iscsi:
  - ip: 192.168.10.1/24
    port: ct0.eth4
  - ip: 192.168.20.1/24
    port: ct0.eth5
  - ip: 192.168.10.2/24
    port: ct1.eth4
  - ip: 192.168.20.2/24
    port: ct1.eth5

iscsi_gateway: #none
iscsi_mtu: 9000

dns_address:
  - 10.119.2.240

dns_domain: fsv.local

ntp_servers:
  - 172.20.10.119
  - ntp1.pool.org
  - ntp2.pool.org

phonehome: present
remote_assist: enable

proxy_server: relay.flashstack.local
proxy_port: 80

smtp_relay: smtp.flashstack.local
smtp_domain: flashstack.local

alert_address: alert@flashstack.local

mgmt_ad_uri:
  - "ldap://1.2.3.5"
  - "ldap://1.2.3.6"
mgmt_ad_base: "DC=acme,DC=lab"
mgmt_ad_user: "svc.ldap"
mgmt_ad_password: "P@ssw0rd!"

ad_admin_base: "OU=Groups,OU=Acme Lab"
ad_admin_group: "Acme Array Admins"
ad_storage_base: null
ad_storage_group: null
ad_ops_base: null
ad_ops_group: null
ad_ro_base: "OU=Groups,OU=Acme Lab"
ad_ro_group: "Acme Array ReadOnly"

esx_cluster_fcp: FSV-M7-HostGroup
esx_cluster_iscsi: FSV-M7-HostGroup-iSCSI
esx_cluster_nvme: FSV-M7-HostGroup-FC-NVMe
esx_hosts_iscsi:
  FSV-ESXi-Host-13:
    iqn: iqn.2010-11.com.flashstack:ac09-ucshost:1
    protocol: iscsi
  # VM-Infra-Host-iSCSI-01:
  #   iqn: iqn.1998-01.com.vmware:esxi1-2bef2660
  #   protocol: iscsi
  # VM-Infra-Host-iSCSI-02:
  #   iqn: iqn.1998-01.com.vmware:esxi2-2ce296a0
  #   protocol: iscsi
  # VM-Infra-Host-iSCSI-03:
  #   iqn: iqn.1998-01.com.vmware:esxi3-28f0242c
  #   protocol: iscsi

# Specific WWPN for each host, one per fabric
esx_hosts_fc:
  FSV-ESXi-Host-11:
    wwns:
      - 20:00:00:B4:AC:09:0A:02
      - 20:00:00:B4:AC:09:0B:02
    protocol: fc
  # VM-Infra-Host-FCP-11:
  #   wwns:
  #     - 00:00:00:00:00:00:00:01
  #     - 00:00:00:00:00:00:00:02
  #   protocol: fc
  # VM-Infra-Host-FCP-13:
  #   wwns:
  #     - 00:00:00:00:00:00:00:03
  #     - 00:00:00:00:00:00:00:04
  #   protocol: fc

esx_hosts_nvme:
  VM-Infra-Host-NVMe-01:
    nqn: nqn.2014-08.com.cisco.flashstack:nvme:esxi-1
    protocol: nvme
  VM-Infra-Host-NVMe-02:
    nqn: nqn.2014-08.com.cisco.flashstack:nvme:esxi-2
    protocol: nvme
  VM-Infra-Host-NVMe-03:
    nqn: nqn.2014-08.com.cisco.flashstack:nvme:esxi-3
    protocol: nvme
datastore_count: 5
datastore_swap: 0
datastore_swap_size: 500G
datastore_size: 1T
bfs_size: 120G

