---
# iSCSI Adapter Policy
- name: "Configure iSCSI Adapter Policy"
  vars:
    api_info: &api_info
      api_private_key: "{{ intersight_api_private_key }}"
      api_key_id: "{{ intersight_api_key_id }}"
      api_uri: "{{ api_uri | default(omit) }}"
      validate_certs: "{{ validate_certs | default(omit) }}"
      state: "{{ state | default(omit) }}"

  cisco.intersight.intersight_rest_api:
      <<: *api_info
      resource_path: /vnic/IscsiAdapterPolicies
      query_params:
         $filter: "Name eq '{{ name_of_iscsi_adapter_policy }}'"
      api_body: {
        "Name": "{{ name_of_iscsi_adapter_policy }}",
        "Description": "{{ description_of_iscsi_adapter_policy }}",

        "Organization": {
           "Moid": "{{ intersight_org.api_response.Moid }}"
         },
         Tags: [{Key: "Provisioned by:", Value: "Intersight-Ansible"},{Key: "Project:", Value: "FSV-{{ prefix }}"}],

        "ConnectionTimeOut": "{{ tcp_connection_time_out }}",
        "DhcpTimeout": "{{ dhcp_timeout }}",
        "LunBusyRetryCount": "{{ lun_busy_retry_count }}"
       }
  register: iscsi_adapter_policy
