---
# Procedures to setup iSCSI paramters on the ESXi Hosts
#
- name:  Add the NTP Server(s) to the ESXi Hosts
  ansible.builtin.include_tasks: add_esxi_ntp.yml

- name:  Modify the iSCSI-A vSwitch and add iSCSI-B vSwitch
  ansible.builtin.include_tasks: modify_esxi_iscsi_vswitch.yml

- name:  Create the iSCSI-B Port-Group on iSCSI-B vSwitch
  ansible.builtin.include_tasks: create_esxi_iscsiB_PG.yml

- name:  Modify the iSCSI-A VMK MTU and create iSCSI-B VMK
  ansible.builtin.include_tasks: create_esxi_iscsi_vmk.yml

- name:  Add iSCSI Targets for Multi Path
  ansible.builtin.include_tasks: add_esxi_iscsi_targets.yml

- name:  Rescan HBA's for the ESXi host and refresh storage system objects
  ansible.builtin.include_tasks: rescan_esxi_iscsi_HBA.yml

