---
- name: Rescan HBA's for the ESXi host and refresh storage system objects
  community.vmware.vmware_host_scanhba:
    hostname: '{{ inventory_hostname }}'
    username: '{{ esxi_username }}'
    password: '{{ esxi_password }}'
    validate_certs: false
    esxi_hostname: '{{ inventory_hostname }}'
    refresh_storage: true
  delegate_to: localhost
  when: configure_iscsi is defined
